### PR TITLE
Added code to support old android devices.

### PR DESCRIPTION
**Pull request by kashifo**

### CODE REVIEW

**Comment by kashifo** [comment]
Hi are you there? I've tested with this update, it is working fine on Android 2.3 to 6.0.

**Comment by gsurrel** [comment]
Yes, I am still here, but I don't have much time for testing. I'll allocate 30 minutes to it right now, I hop it will be enough.

Thanks for the compatibility work :)

**Comment by kashifo** [comment]
Okay, It's my pleasure.

**Comment by gsurrel** [comment]
I have some more things to change, I'll hold it in the meantime. I think it will need some pen & paper thinking not to screw up everything.

**Comment by kashifo** [comment]
Sure, No problem. you're the owner.

**Comment by gsurrel** [comment]
I did some refactoring so the code is a bit more compact and readable, plus I kept the possibility to have different notification sounds and patterns for every notification depending on its type.
Could you please check if I haven't messed up something? From my tests, it seems to be working.

**Comment by kashifo** [comment]
I checked it, you really made the code clean and readable, good job

**Pull request merged**
